export const APPLICATION_LOG_EVENTS = {
  SERVER_ACTION_START_ADVENTURE_VALIDATION_FAILED: "server_action.start_adventure.validation_failed",
  SERVER_ACTION_START_ADVENTURE_UNAUTHENTICATED_REDIRECT: "server_action.start_adventure.unauthenticated_redirect",
  SERVER_ACTION_START_ADVENTURE_SUCCESS: "server_action.start_adventure.success",
  SERVER_ACTION_START_ADVENTURE_RECOVERABLE_FAILURE: "server_action.start_adventure.recoverable_failure",
  SERVER_ACTION_INTERVIEW_ANSWER_VALIDATION_FAILED: "server_action.interview_answer.validation_failed",
  SERVER_ACTION_INTERVIEW_ANSWER_UNAUTHENTICATED_REDIRECT: "server_action.interview_answer.unauthenticated_redirect",
  SERVER_ACTION_INTERVIEW_ANSWER_SUCCESS: "server_action.interview_answer.success",
  SERVER_ACTION_INTERVIEW_ANSWER_EXPECTED_ERROR: "server_action.interview_answer.expected_error",
  SERVER_ACTION_INTERVIEW_ANSWER_RECOVERABLE_FAILURE: "server_action.interview_answer.recoverable_failure",
  SERVER_ACTION_FORGE_RETRY_VALIDATION_FAILED: "server_action.forge_retry.validation_failed",
  SERVER_ACTION_FORGE_RETRY_UNAUTHENTICATED_REDIRECT: "server_action.forge_retry.unauthenticated_redirect",
  SERVER_ACTION_FORGE_RETRY_STARTED: "server_action.forge_retry.started",
  SERVER_ACTION_FORGE_RETRY_SUCCESS: "server_action.forge_retry.success",
  SERVER_ACTION_FORGE_RETRY_FAILURE: "server_action.forge_retry.failure",
  AUTH_SIGN_IN_SUCCESS: "auth.sign_in.success",
  ADVENTURE_DRAFT_CREATE_SUCCESS: "adventure_draft.create.success",
  INTERVIEW_ANSWER_PERSISTED: "interview.answer.persisted",
  INTERVIEW_TURN_COMPLETED: "interview.turn.completed",
  INTERVIEW_TURN_RECOVERABLE_FAILURE: "interview.turn.recoverable_failure",
  INTERVIEW_READINESS_CHANGED: "interview.readiness.changed",
  INTERVIEW_CONFIRMED: "interview.confirmed",
  FORGE_ARTIFACT_GENERATION_NOT_FOUND: "forge.artifact_generation.not_found",
  FORGE_ARTIFACT_GENERATION_NOT_CONFIRMED: "forge.artifact_generation.not_confirmed",
  FORGE_ARTIFACT_GENERATION_REUSED_EXISTING: "forge.artifact_generation.reused_existing",
  FORGE_ARTIFACT_GENERATION_STARTED: "forge.artifact_generation.started",
  FORGE_ARTIFACT_GENERATION_FAILED: "forge.artifact_generation.failed",
  FORGE_ARTIFACT_GENERATION_COMPLETED: "forge.artifact_generation.completed",
  FORGE_GENERATE_ADVENTURE_PROVIDER_STARTED: "forge.generate_adventure.provider_started",
  FORGE_GENERATE_ADVENTURE_PROVIDER_COMPLETED: "forge.generate_adventure.provider_completed",
  FORGE_GENERATE_ADVENTURE_PROVIDER_FAILED: "forge.generate_adventure.provider_failed",
  FORGE_GENERATE_ADVENTURE_OUTPUT_INVALID: "forge.generate_adventure.output_invalid",
  AI_OPENAI_REQUEST_COMPLETED: "ai.openai.request.completed",
  AI_OPENAI_REQUEST_FAILED: "ai.openai.request.failed",
  AI_OPENAI_OUTPUT_INVALID: "ai.openai.output.invalid",
  AI_OPENAI_PAYLOAD_DEBUG: "ai.openai.payload.debug",
} as const;

export type ApplicationLogEventName =
  (typeof APPLICATION_LOG_EVENTS)[keyof typeof APPLICATION_LOG_EVENTS];
